import { useEffect, useState } from 'react';
import { Bookmark, FileText, Trash2, Copy, Filter, Sparkles, X } from 'lucide-react';
import { api } from '../lib/api';
import { useToast } from '../components/Toast';
import type { Bookmark as BookmarkType, AIBrief } from '../types';

function timeAgo(timestamp: string): string {
  const diff = Date.now() - new Date(timestamp + 'Z').getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export default function ResearchPage() {
  const [bookmarks, setBookmarks] = useState<BookmarkType[]>([]);
  const [matterFilter, setMatterFilter] = useState('');
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  const [briefTopic, setBriefTopic] = useState('');
  const [showBriefModal, setShowBriefModal] = useState(false);
  const [brief, setBrief] = useState<AIBrief | null>(null);
  const [briefLoading, setBriefLoading] = useState(false);
  const { toast } = useToast();

  const load = () => {
    api.getBookmarks(matterFilter || undefined).then((r) => setBookmarks(r.bookmarks)).catch(console.error);
  };

  useEffect(load, [matterFilter]);

  const handleDelete = async (id: number) => {
    await api.deleteBookmark(id);
    toast('info', 'Bookmark removed');
    load();
  };

  const copyForBrief = (b: BookmarkType) => {
    const cite = `"${b.text.substring(0, 300)}${b.text.length > 300 ? '...' : ''}" ${b.document_name}${b.page ? `, at p. ${b.page}` : ''}.`;
    navigator.clipboard.writeText(cite);
    toast('success', 'Copied for brief');
  };

  const exportMemo = () => {
    const lines = [
      'LEGAL RESEARCH MEMORANDUM',
      `Date: ${new Date().toLocaleDateString()}`,
      matterFilter ? `Matter: ${matterFilter}` : '',
      '',
      '=' .repeat(60),
      '',
      ...bookmarks.map((b, i) => [
        `${i + 1}. ${b.document_name}${b.page ? `, Page ${b.page}` : ''}`,
        b.query ? `   Query: "${b.query}"` : '',
        b.note ? `   Note: ${b.note}` : '',
        `   Excerpt: "${b.text}"`,
        '',
      ]).flat(),
      '=' .repeat(60),
      'Generated by Verbatim — Smart Document Search',
    ].filter(Boolean);

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `research-memo${matterFilter ? `-${matterFilter}` : ''}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast('success', 'Memo exported');
  };

  const toggleSelect = (id: number) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const handleGenerateBrief = async () => {
    if (!briefTopic.trim()) { toast('error', 'Enter a topic'); return; }
    const selected = bookmarks.filter((b) => selectedIds.has(b.id));
    if (selected.length === 0) { toast('error', 'Select at least one bookmark'); return; }
    setBriefLoading(true);
    try {
      const result = await api.generateBrief(
        briefTopic,
        selected.map((b) => ({ document_name: b.document_name, page: b.page, text: b.text })),
      );
      setBrief(result);
    } catch (e: unknown) {
      toast('error', e instanceof Error ? e.message : String(e));
    } finally {
      setBriefLoading(false);
    }
  };

  // Get unique matters for filter
  const matters = [...new Set(bookmarks.map((b) => b.matter).filter(Boolean))];

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold text-navy-900">Research</h1>
          <p className="text-navy-500 mt-1">Saved excerpts, citations, and notes for your matters</p>
        </div>
        <div className="flex items-center gap-2">
          {bookmarks.length > 0 && selectedIds.size > 0 && (
            <button
              onClick={() => setShowBriefModal(true)}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-gold-500 text-navy-900 font-medium rounded-lg hover:bg-gold-400 transition-colors"
            >
              <Sparkles size={14} /> Generate AI Brief ({selectedIds.size})
            </button>
          )}
          {bookmarks.length > 0 && (
            <button
              onClick={exportMemo}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-navy-800 text-white rounded-lg hover:bg-navy-700 transition-colors"
            >
              Export Memo
            </button>
          )}
        </div>
      </div>

      {/* Matter filter */}
      {matters.length > 0 && (
        <div className="flex items-center gap-3 mb-6">
          <Filter size={14} className="text-navy-400" />
          <span className="text-xs text-navy-400 font-medium uppercase tracking-wider">Matter:</span>
          <button
            onClick={() => setMatterFilter('')}
            className={`px-3 py-1 text-xs rounded-full transition-colors ${
              !matterFilter ? 'bg-navy-800 text-white' : 'bg-white border border-navy-200 text-navy-600 hover:border-navy-400'
            }`}
          >
            All
          </button>
          {matters.map((m) => (
            <button
              key={m}
              onClick={() => setMatterFilter(m)}
              className={`px-3 py-1 text-xs rounded-full transition-colors ${
                matterFilter === m ? 'bg-navy-800 text-white' : 'bg-white border border-navy-200 text-navy-600 hover:border-navy-400'
              }`}
            >
              {m}
            </button>
          ))}
        </div>
      )}

      {bookmarks.length === 0 ? (
        <div className="bg-white rounded-lg border border-navy-200 p-12 text-center">
          <Bookmark size={40} className="mx-auto text-navy-200 mb-4" />
          <h2 className="text-lg font-medium text-navy-600 mb-2">No saved research yet</h2>
          <p className="text-sm text-navy-400 max-w-md mx-auto">
            Save excerpts while searching or using the Clause Finder. They'll appear here organized by matter for easy brief preparation.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          <p className="text-sm text-navy-500">{bookmarks.length} saved item{bookmarks.length !== 1 ? 's' : ''}</p>
          {bookmarks.map((b) => (
            <div key={b.id} className="bg-white border border-navy-200 rounded-lg shadow-sm">
              <div className="flex items-center justify-between px-5 py-3 border-b border-navy-50">
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    checked={selectedIds.has(b.id)}
                    onChange={() => toggleSelect(b.id)}
                    className="rounded border-navy-300 text-gold-500 focus:ring-gold-400"
                  />
                  <FileText size={14} className="text-navy-500" />
                  <span className="text-sm font-semibold text-navy-800">{b.document_name}</span>
                  {b.page && <span className="text-xs text-navy-400">p. {b.page}</span>}
                  {b.matter && (
                    <span className="text-xs bg-gold-100 text-gold-700 px-2 py-0.5 rounded-full">{b.matter}</span>
                  )}
                </div>
                <span className="text-xs text-navy-400">{timeAgo(b.created_at)}</span>
              </div>
              <div className="px-5 py-3">
                {b.query && <p className="text-xs text-navy-400 mb-1">From search: "{b.query}"</p>}
                <p className="text-sm text-navy-700 leading-relaxed">{b.text}</p>
                {b.note && <p className="text-xs text-navy-500 mt-2 italic">Note: {b.note}</p>}
              </div>
              <div className="px-5 py-2 border-t border-navy-50 flex gap-3">
                <button
                  onClick={() => copyForBrief(b)}
                  className="text-xs text-navy-500 hover:text-navy-700 transition-colors flex items-center gap-1"
                >
                  <Copy size={12} /> Copy for Brief
                </button>
                <button
                  onClick={() => handleDelete(b.id)}
                  className="text-xs text-navy-400 hover:text-red-600 transition-colors flex items-center gap-1 ml-auto"
                >
                  <Trash2 size={12} /> Remove
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* AI Brief Modal */}
      {showBriefModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="bg-white rounded-xl shadow-xl max-w-3xl w-full max-h-[85vh] overflow-y-auto">
            <div className="flex items-center justify-between px-6 py-4 border-b border-navy-100">
              <div className="flex items-center gap-2">
                <Sparkles size={18} className="text-gold-500" />
                <h2 className="text-lg font-bold text-navy-900">Generate AI Brief</h2>
              </div>
              <button onClick={() => { setShowBriefModal(false); setBrief(null); }} className="text-navy-400 hover:text-navy-600">
                <X size={20} />
              </button>
            </div>
            <div className="p-6 space-y-4">
              {!brief ? (
                <>
                  <div>
                    <label className="text-sm font-medium text-navy-700 mb-1 block">Topic / Legal Question</label>
                    <input
                      type="text"
                      value={briefTopic}
                      onChange={(e) => setBriefTopic(e.target.value)}
                      placeholder="e.g. Analysis of indemnification provisions across agreements"
                      className="w-full px-4 py-2.5 border border-navy-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gold-400"
                    />
                  </div>
                  <p className="text-sm text-navy-500">{selectedIds.size} bookmark{selectedIds.size !== 1 ? 's' : ''} selected as research sources.</p>
                  <button
                    onClick={handleGenerateBrief}
                    disabled={briefLoading}
                    className="flex items-center gap-2 px-6 py-2.5 text-sm bg-gold-500 text-navy-900 font-medium rounded-lg hover:bg-gold-400 disabled:opacity-50 transition-colors"
                  >
                    <Sparkles size={14} /> {briefLoading ? 'Generating...' : 'Generate Brief'}
                  </button>
                </>
              ) : (
                <div className="space-y-4 text-sm text-navy-700">
                  <h3 className="text-lg font-bold text-navy-900">{brief.title}</h3>
                  <div>
                    <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wider mb-1">Issue Presented</h4>
                    <p>{brief.issue}</p>
                  </div>
                  <div>
                    <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wider mb-1">Brief Answer</h4>
                    <p>{brief.brief_answer}</p>
                  </div>
                  <div>
                    <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wider mb-1">Discussion</h4>
                    <p className="whitespace-pre-wrap leading-relaxed">{brief.discussion}</p>
                  </div>
                  <div>
                    <h4 className="text-xs font-semibold text-navy-500 uppercase tracking-wider mb-1">Conclusion</h4>
                    <p>{brief.conclusion}</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
