import { spawn } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";
import { env } from "@/lib/env";
import { AppError } from "@/lib/errors";

/**
 * Converts a DOCX buffer to a PDF buffer using headless LibreOffice.
 * Uses an isolated temporary UserInstallation profile directory to avoid lockups.
 */
export async function convertDocxToPdf(docxBuffer: Buffer): Promise<Buffer> {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "verbatim_docx_"));
  const tempProfileDir = fs.mkdtempSync(path.join(os.tmpdir(), "verbatim_profile_"));
  const inputDocxPath = path.join(tempDir, "input.docx");
  const outputPdfPath = path.join(tempDir, "input.pdf");

  fs.writeFileSync(inputDocxPath, docxBuffer);

  const normalizedProfileUri = "file:///" + tempProfileDir.replace(/\\/g, "/");
  const sofficeBinary = env.SOFFICE_PATH;

  const args = [
    `-env:UserInstallation=${normalizedProfileUri}`,
    "--headless",
    "--convert-to",
    "pdf",
    "--outdir",
    tempDir,
    inputDocxPath,
  ];

  try {
    const exitCode = await new Promise<number>((resolve, reject) => {
      const child = spawn(sofficeBinary, args, {
        windowsHide: true,
        stdio: ["ignore", "pipe", "pipe"],
      });

      const timeout = setTimeout(() => {
        child.kill("SIGKILL");
        reject(
          new AppError(
            "CONVERSION_FAILED",
            "DOCX conversion timed out after 45 seconds.",
            500
          )
        );
      }, 45000);

      let stderr = "";
      child.stderr?.on("data", (chunk) => {
        stderr += chunk.toString();
      });

      child.on("close", (code) => {
        clearTimeout(timeout);
        if (code === 0) {
          resolve(0);
        } else {
          reject(
            new AppError(
              "CONVERSION_FAILED",
              `LibreOffice exited with code ${code}: ${stderr}`,
              500
            )
          );
        }
      });

      child.on("error", (err) => {
        clearTimeout(timeout);
        reject(
          new AppError(
            "CONVERSION_FAILED",
            `Failed to spawn LibreOffice: ${err.message}`,
            500
          )
        );
      });
    });

    if (exitCode !== 0 || !fs.existsSync(outputPdfPath)) {
      throw new AppError(
        "CONVERSION_FAILED",
        "Converted PDF was not generated by LibreOffice.",
        500
      );
    }

    const pdfBuffer = fs.readFileSync(outputPdfPath);
    return pdfBuffer;
  } finally {
    // Cleanup temporary files and profile
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
    try {
      fs.rmSync(tempProfileDir, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  }
}
